# Generated by Django 5.2.17 on 2026-08-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, verbose_name='会话ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI 助手'), ('system', '系统')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'db_table': 'chat_message',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='idx_session_time')],
            },
        ),
    ]
